services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app/client
      - ./server:/app/server
      - ./shared:/app/shared
      - /app/node_modules
    restart: unless-stopped